export default {
    GET_MOVIES: 'GET_MOVIES',
    SET_MOVIES: 'SET_MOVIES',
    GET_MOVIES_FAILURE: 'GET_MOVIES_FAILURE',
    ADD_MOVIE: 'ADD_MOVIE',
    UPDATE_MOVIE: 'UPDATE_MOVIE',
    DELETE_MOVIE: 'DELETE_MOVIE',
    FILTER_MOVIES: 'FILTER_MOVIES',
    SORT_MOVIES: 'SORT_MOVIES',
    SELECT_MOVIE: 'SELECT_MOVIE',
    SET_ACTIVE_FILTER: 'SET_ACTIVE_FILTER',
}